language: node_js   #设置语言
node_js: 
  - 10  # use nodejs v10 LTS
cache: npm
    directories:
        - node_modules    #据说可以减少travis构建时间
before_install:
  - npm install  hexo-cli -g
  - npm install hexo --save
  - echo 'PATH="$PATH:./node_modules/.bin"' >> ~/.profile
install:
  - npm install   #安装hexo及插件
before_script:
  - git clone --branch master https://github.com/HZNU-InfoSecurityLab/HZNU-InfoSecurityLab.github.io.git public #拉取master当前页面到本地develop
script:
  - hexo generate   #生成静态整站
after_script:
  - cd ./public  #生成的静态页面会存储在public目录下
  - cat index.html #log查看
  - git init  #初始化本地库，master工作区只剩下生成的public
  - git config user.name "MAllstar"   #填入GitHub的用户名，travis 通过 MAllstar 账户（已设置令牌）对github项目进行自动化构建
  - git config user.email "1160809932@qq.com"   #填入GitHub的邮箱地址
  - git add .
  - git commit -m "update by Travis-CI" #自动构建后的内容将全部以此信息提交
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_token就是在travis中设置的token, 强制覆盖github上的master分支
branches:
  only:
  - develop  #只监测这个分支，一有动静就拉取代码开始构建
env:
    global:
        - GH_REF: github.com/HZNU-InfoSecurityLab/HZNU-InfoSecurityLab.github.io.git